server:
  port: 8080

spring:
  datasource:
    username: root
    password: MySQL@2019
    url: jdbc:mysql://47.94.36.91:3306/bisaibang?useUnicode=true&amp&characterEncoding=UTF8&amp&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver


#showSql
logging:
  level:
    org.lanqiao:
      mapper: debug